# Generated by Django 4.0.5 on 2022-06-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_examination_altered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='altered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
